package org.example;

public enum MessageType {
    HANDSHAKE,
    HANDSHAKEKEYRETURN,

    PEERLIST,

    PEERLISTRETURN,

    BLOCKCHAINREQUEST,

    BLOCKCHAINRESPONSE,
    UTXOPOOLINITIALIZATION, TRANSACTION, REQUESTTRANSPOOL, REQUESTUTXOPOOL, RESPONSETRANSPOOL, RESPONSEUTXOPOOL, BLOCK,


    }